# PyTorch

## Example 1

---

In [1]:
import torch

print(torch.backends.mps.is_available()) #the MacOS is higher than 12.3+
print(torch.backends.mps.is_built()) #MPS is activated

True
True


In [2]:
dtype = torch.float
device = torch.device("mps")
# device = torch.device("cpu")  # Execute all calculations on the CPU
# device = torch.device("cuda:0")  # Executes all calculations on the GPU

In [3]:
# Create a tensor and fill it with random numbers
a = torch.randn(2, 3, device=device, dtype=dtype)
print(a)
# Output: tensor([[-1.1884,  0.8498, -1.7129],
#                  [-0.8816,  0.1944,  0.5847]])

tensor([[-2.1669,  0.8264, -0.0069],
        [-1.9832,  1.3697,  1.3889]], device='mps:0')


In [4]:
b = torch.randn(2, 3, device=device, dtype=dtype)
print(b)
# Output: tensor([[ 0.7178, -0.8453, -1.3403],
#                  [ 1.3262,  1.1512, -1.7070]])

tensor([[ 2.1814,  0.6680, -1.2371],
        [-0.8202,  0.3957,  0.3842]], device='mps:0')


In [5]:
print(a * b)
# Output: tensor([[-0.8530, -0.7183,  2.58],
#                  [-1.1692,  0.2238, -0.9981]])

tensor([[-4.7268,  0.5520,  0.0085],
        [ 1.6266,  0.5420,  0.5337]], device='mps:0')


In [6]:
print(a.sum()) 
# Output: tensor(-2.1540)

tensor(-0.5719, device='mps:0')


In [7]:
print(a[1,2]) # Output of the element in the third column of the second row (zero based)
# Output: tensor(0.5847)

tensor(1.3889, device='mps:0')


In [8]:
print(a.max())
# Output: tensor(0.8498)

tensor(1.3889, device='mps:0')


## Example II

___

In [9]:
import torch
from torch import nn # Import the nn sub-module from PyTorch

class NeuralNetwork(nn.Module):  # Neural networks are defined as classes
    def __init__(self):  # Layers and variables are defined in the __init__ method
        super().__init__()  # Must be in every network.
        self.flatten = nn.Flatten()   # Construct a flattening layer.
        self.linear_relu_stack = nn.Sequential(  # Construct a stack of layers.
            nn.Linear(28*28, 512),  # Linear Layers have an input and output shape
            nn.ReLU(),  # ReLU is one of many activation functions provided by nn
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10), 
        )

    def forward(self, x):  # This function defines the forward pass.
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [10]:
from torch.utils.data import DataLoader, TensorDataset
import torch.optim as optim

# Create a dummy dataset
batch_size = 64
dummy_data = torch.randn(batch_size, 28, 28)  # 64 samples of 28x28 images
dummy_labels = torch.randint(0, 10, (batch_size,))  # 64 random labels in the range [0, 9]

# Create a DataLoader
dataset = TensorDataset(dummy_data, dummy_labels)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Instantiate the model, loss function, and optimizer
model = NeuralNetwork()
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop (for one epoch)
for batch, (X, y) in enumerate(dataloader):
    # Forward pass: compute predicted y by passing X to the model
    pred = model(X)
    
    # Compute and print loss
    loss = criterion(pred, y)
    print(f"Batch {batch}, Loss: {loss.item()}")
    
    # Zero gradients, perform a backward pass, and update the weights
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


Batch 0, Loss: 2.3177261352539062


# References

- [ ] [WikiPedia: PyTorch](https://en.wikipedia.org/wiki/PyTorch)